/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MorningIntelligenceRouteImport } from './routes/morning-intelligence'
import { Route as InvestigationV2RouteImport } from './routes/investigation-v2'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as CriminalNetworkRouteImport } from './routes/criminal-network'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MorningIntelligenceRoute = MorningIntelligenceRouteImport.update({
  id: '/morning-intelligence',
  path: '/morning-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationV2Route = InvestigationV2RouteImport.update({
  id: '/investigation-v2',
  path: '/investigation-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const CriminalNetworkRoute = CriminalNetworkRouteImport.update({
  id: '/criminal-network',
  path: '/criminal-network',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/criminal-network': typeof CriminalNetworkRoute
  '/investigation': typeof InvestigationRoute
  '/investigation-v2': typeof InvestigationV2Route
  '/morning-intelligence': typeof MorningIntelligenceRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/criminal-network': typeof CriminalNetworkRoute
  '/investigation': typeof InvestigationRoute
  '/investigation-v2': typeof InvestigationV2Route
  '/morning-intelligence': typeof MorningIntelligenceRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/criminal-network': typeof CriminalNetworkRoute
  '/investigation': typeof InvestigationRoute
  '/investigation-v2': typeof InvestigationV2Route
  '/morning-intelligence': typeof MorningIntelligenceRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/criminal-network'
    | '/investigation'
    | '/investigation-v2'
    | '/morning-intelligence'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/criminal-network'
    | '/investigation'
    | '/investigation-v2'
    | '/morning-intelligence'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/criminal-network'
    | '/investigation'
    | '/investigation-v2'
    | '/morning-intelligence'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CriminalNetworkRoute: typeof CriminalNetworkRoute
  InvestigationRoute: typeof InvestigationRoute
  InvestigationV2Route: typeof InvestigationV2Route
  MorningIntelligenceRoute: typeof MorningIntelligenceRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morning-intelligence': {
      id: '/morning-intelligence'
      path: '/morning-intelligence'
      fullPath: '/morning-intelligence'
      preLoaderRoute: typeof MorningIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation-v2': {
      id: '/investigation-v2'
      path: '/investigation-v2'
      fullPath: '/investigation-v2'
      preLoaderRoute: typeof InvestigationV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criminal-network': {
      id: '/criminal-network'
      path: '/criminal-network'
      fullPath: '/criminal-network'
      preLoaderRoute: typeof CriminalNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CriminalNetworkRoute: CriminalNetworkRoute,
  InvestigationRoute: InvestigationRoute,
  InvestigationV2Route: InvestigationV2Route,
  MorningIntelligenceRoute: MorningIntelligenceRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
